### ISSUE TITLE
Chapter 9.6 heading is not descriptive enough

### ISSUE THREAD

**Issue by meling** [remzi-arpacidusseau/ostep-typos#1]
(first, @remzi-arpacidusseau sorry if this isn't how you want to process reported suggestions/typos... but there wasn't any instructions in the readme.md file...)

`9.6 Why Not Deterministic?`
would be more clear if it was changed to
`9.6 Stride Scheduling`
or something similar, since that's what the chapter is explaining.

**Comment by remzi-arpacidusseau** [comment]
good idea. fixed!
