### ISSUE TITLE
cpu-api, references, [QI15] missing letter in french quote

### ISSUE THREAD

**Issue by slk333** [remzi-arpacidusseau/ostep-typos#14]
"grande responsabilit
-> 
“grande responsabilit**é**

source: https://en.wikipedia.org/wiki/With_great_power_comes_great_responsibility

**Comment by remzi-arpacidusseau** [comment]
ah, good eye. Fixed! A person to thank in the printed book preface?
Remzi

**Comment by slk333** [comment]
Hi, don't need to thank me, I am the one to thank you! Cheers :)
