### ISSUE TITLE
loop.s in ostep-homework/thread-locks/README.md

### ISSUE THREAD

**Issue by gurugio** [remzi-arpacidusseau/ostep-typos#15]
'jgte .top' command of the loop.s needs to be replaced with 'jgt .top'.

jgte command loops when dx is 0 and exits the loops when dx is -1.

**Comment by remzi-arpacidusseau** [comment]
Thanks! Your update will propagate to the ostep site and printed book soon,
and your name will also soon appear in the preface. Much appreciated!

**Comment by gurugio** [comment]
My name is "Gioh Kim".
Thank you.
