### ISSUE TITLE
create folder "vmm-intro" for receiving typos/bugs files and 1st typo

### ISSUE THREAD

**Issue by jmcruzGH** [remzi-arpacidusseau/ostep-typos#25]
A folder named "vmm-intro" for chapter "Appendix B. Virtual Machine Monitors" should be created, so that, within it, files for bugs/typos can be created.
First typo in this chapter is in p.10, B.5 The Information Gap:
where it is:
     It makes sense to spin like this if the OS in charge of the entire machine and thus knows ...
it should be:
     It makes sense to spin like this if the OS is in charge of the entire machine and thus knows ...

**Comment by remzi-arpacidusseau** [comment]
Thanks! Your update will propagate to the ostep site and printed book soon,
and your name will also soon appear in the preface. Much appreciated!
