### ISSUE TITLE
Semaphores - typo in Fig 31.17 Zemaphore implementation? 

### ISSUE THREAD

**Issue by ambareeshsrja16** [remzi-arpacidusseau/ostep-typos#32]
Figure 31.17 Implementing Zemaphores with Locks and CVs:
![image](https://user-images.githubusercontent.com/39631487/125495351-f903b3ab-9a44-452b-848f-7d7e95ac35b5.png)

In function Zem_Wait, the code checks first if the value is <=0 and waits. After which it decrements the value. However from the defintions earlier (say figure 31.2):

![image](https://user-images.githubusercontent.com/39631487/125495455-a12befe7-98a2-472f-9047-8d229f223357.png)

sem_wait is supposed to decrement the value first and then wait if the value is negative. Is this a typo or am I missing something here?

**Comment by remzi-arpacidusseau** [comment]
As the text (kind of) explains, this impl is a little different than the pure sema definition...
