### ISSUE TITLE
SPTF discussion missing from chapter Hard Disk Drives

### ISSUE THREAD

**Issue by ambareeshsrja16** [remzi-arpacidusseau/ostep-typos#37]
From the hardcover (and the online version) SPTF discussion section is missing. _"Thus SPTF is usually performed inside a drive, described below"_ is followed by a different section. 

PFA Screenshot

![image](https://user-images.githubusercontent.com/39631487/128955507-5f6055d8-327e-41b3-bc18-5a706bd6ee22.png)

**Comment by remzi-arpacidusseau** [comment]
don't quite understand; two paragraphs later, the book talks about implementing SPTF in the disk itself.... ?
