### ISSUE TITLE
semaphores: Semaphores For Ordering (page5) suggestion

### ISSUE THREAD

**Issue by yangjingchi** [remzi-arpacidusseau/ostep-typos#45]
just a suggestion for the following sentence.  

"The only way this will happen is if the value of the semaphore is not greater than 0; hence, 0 is the initial value."

I think it's better this way

The only way this will happen is if the value of the semaphore is **less** than 0; **however since sem_wait() will first decrement the value before checking it,** hence, 0 is the initial value."

**Comment by remzi-arpacidusseau** [comment]
eh I dunno. I can see why it is the way it is. I will think on it. thanks!
