### ISSUE TITLE
bash: syntax error near unexpected token `;'

### ISSUE THREAD

**Issue by cpanceac** [remzi-arpacidusseau/ostep-typos#79]
On page 6, when executing:

$ ./mem &; ./mem &

bash returns error: 

bash: syntax error near unexpected token `;'

It works fine if we remove the ';'

**Comment by remzi-arpacidusseau** [comment]
yeah this was from my old csh stuff, and has since been fixed to work across different shells (the ; works in zsh and csh but not bash I guess)
